//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSky.GlobalResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UICtrlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UICtrlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSky.GlobalResources.Properties.UICtrlResources", typeof(UICtrlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA.
        /// </summary>
        public static string AAA {
            get {
                return ResourceManager.GetString("AAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide category name and click OK..
        /// </summary>
        public static string AddCategoryErrMsg1 {
            get {
                return ResourceManager.GetString("AddCategoryErrMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please provide category name or click Cancel to exit..
        /// </summary>
        public static string AddCategoryErrMsg2 {
            get {
                return ResourceManager.GetString("AddCategoryErrMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new level(s) separated by comma (e.g. level1, level2, level3):.
        /// </summary>
        public static string AddFactorLevelMsg {
            get {
                return ResourceManager.GetString("AddFactorLevelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Model Class Window.
        /// </summary>
        public static string AddModelClassWinTitle {
            get {
                return ResourceManager.GetString("AddModelClassWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To save output and/or syntax before exiting click YES..
        /// </summary>
        public static string AppExitConfirmMsg {
            get {
                return ResourceManager.GetString("AppExitConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click NO to exit without saving..
        /// </summary>
        public static string AppExitConfirmMsg2 {
            get {
                return ResourceManager.GetString("AppExitConfirmMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string AppExitConfirmMsgTitle {
            get {
                return ResourceManager.GetString("AppExitConfirmMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured. App will Exit..
        /// </summary>
        public static string AppExitOnErrorMsg {
            get {
                return ResourceManager.GetString("AppExitOnErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting Application!.
        /// </summary>
        public static string AppExitOnErrorMsgTitle {
            get {
                return ResourceManager.GetString("AppExitOnErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example 1: foreign.
        /// </summary>
        public static string AskPkgNameExample1 {
            get {
                return ResourceManager.GetString("AskPkgNameExample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example 2: foreign, car, MASS.
        /// </summary>
        public static string AskPkgNameExample2 {
            get {
                return ResourceManager.GetString("AskPkgNameExample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string buttonAdd {
            get {
                return ResourceManager.GetString("buttonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Class.
        /// </summary>
        public static string buttonAddClass {
            get {
                return ResourceManager.GetString("buttonAddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string buttonApply {
            get {
                return ResourceManager.GetString("buttonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string buttonBack {
            get {
                return ResourceManager.GetString("buttonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string buttonBrowse {
            get {
                return ResourceManager.GetString("buttonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string buttonClose {
            get {
                return ResourceManager.GetString("buttonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string buttonConnect {
            get {
                return ResourceManager.GetString("buttonConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Server.
        /// </summary>
        public static string buttonConnectFServer {
            get {
                return ResourceManager.GetString("buttonConnectFServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Defaults.
        /// </summary>
        public static string buttonDefault {
            get {
                return ResourceManager.GetString("buttonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display All Output.
        /// </summary>
        public static string buttonDisplayAllOutput {
            get {
                return ResourceManager.GetString("buttonDisplayAllOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Partial Output.
        /// </summary>
        public static string buttonDisplayPartialOutput {
            get {
                return ResourceManager.GetString("buttonDisplayPartialOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string buttonFindNext {
            get {
                return ResourceManager.GetString("buttonFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string buttonHelp {
            get {
                return ResourceManager.GetString("buttonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Model.
        /// </summary>
        public static string buttonLoadModel {
            get {
                return ResourceManager.GetString("buttonLoadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string buttonMoveDown {
            get {
                return ResourceManager.GetString("buttonMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string buttonMoveUp {
            get {
                return ResourceManager.GetString("buttonMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string buttonRemove {
            get {
                return ResourceManager.GetString("buttonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string buttonReplace {
            get {
                return ResourceManager.GetString("buttonReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string buttonReplaceAll {
            get {
                return ResourceManager.GetString("buttonReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string buttonReset {
            get {
                return ResourceManager.GetString("buttonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Model.
        /// </summary>
        public static string buttonSaveModel {
            get {
                return ResourceManager.GetString("buttonSaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string buttonScore {
            get {
                return ResourceManager.GetString("buttonScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        public static string buttonSyntax {
            get {
                return ResourceManager.GetString("buttonSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add factors to Measure=Scale(Numeric) type..
        /// </summary>
        public static string CantAddFactorToScaleVar {
            get {
                return ResourceManager.GetString("CantAddFactorToScaleVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image Size Dialog.
        /// </summary>
        public static string ChangeImgSizDlgTitle {
            get {
                return ResourceManager.GetString("ChangeImgSizDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string chkboxTables {
            get {
                return ResourceManager.GetString("chkboxTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string chkboxViews {
            get {
                return ResourceManager.GetString("chkboxViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Command Editor.
        /// </summary>
        public static string CommandEditorPanelTitle {
            get {
                return ResourceManager.GetString("CommandEditorPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Window.
        /// </summary>
        public static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your configuration settings will be overwritten by defaults. Do you want to continue?.
        /// </summary>
        public static string ConfSettingOverwriteDefaults {
            get {
                return ResourceManager.GetString("ConfSettingOverwriteDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite with defaults?.
        /// </summary>
        public static string ConfSettingOverwriteDefaultsTitle {
            get {
                return ResourceManager.GetString("ConfSettingOverwriteDefaultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes before closing the window?.
        /// </summary>
        public static string ConfSettingSaveConfirmation {
            get {
                return ResourceManager.GetString("ConfSettingSaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string ConfSettingSaveConfirmTitle {
            get {
                return ResourceManager.GetString("ConfSettingSaveConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma ( , )   [e.g.  1,234].
        /// </summary>
        public static string CSVTXTCommaDeciChar {
            get {
                return ResourceManager.GetString("CSVTXTCommaDeciChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commas ( , ).
        /// </summary>
        public static string CSVTXTCommaText {
            get {
                return ResourceManager.GetString("CSVTXTCommaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Decimal Point Character(for numeric data) :.
        /// </summary>
        public static string CSVTXTDeciCharTitle {
            get {
                return ResourceManager.GetString("CSVTXTDeciCharTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Field Separator:.
        /// </summary>
        public static string CSVTXTFieldSepTitle {
            get {
                return ResourceManager.GetString("CSVTXTFieldSepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First row of a CSV/TXT file contains column headers :.
        /// </summary>
        public static string CSVTXTFirstChkBoxLbl {
            get {
                return ResourceManager.GetString("CSVTXTFirstChkBoxLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string CSVTXTotherText {
            get {
                return ResourceManager.GetString("CSVTXTotherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Point ( . )   [e.g.  1.234].
        /// </summary>
        public static string CSVTXTPointDeciChar {
            get {
                return ResourceManager.GetString("CSVTXTPointDeciChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [For basket format for Apriori/Market Basket Analysis all items are in a single variable/column separated by a delimiter, e.g. Milk, Butter, Brown Bread, ...].
        /// </summary>
        public static string CSVTXTSecChkBoxHint {
            get {
                return ResourceManager.GetString("CSVTXTSecChkBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load all comma separated values in a single column/variable :.
        /// </summary>
        public static string CSVTXTSecChkBoxLbl {
            get {
                return ResourceManager.GetString("CSVTXTSecChkBoxLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolons.
        /// </summary>
        public static string CSVTXTSemicolonText {
            get {
                return ResourceManager.GetString("CSVTXTSemicolonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify:.
        /// </summary>
        public static string CSVTXTspecifyText {
            get {
                return ResourceManager.GetString("CSVTXTspecifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        public static string CSVTXTtabtext {
            get {
                return ResourceManager.GetString("CSVTXTtabtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White space.
        /// </summary>
        public static string CSVTXTwhiteSpaceText {
            get {
                return ResourceManager.GetString("CSVTXTwhiteSpaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV/TXT Open Options Window.
        /// </summary>
        public static string CSVTXTWinTitle {
            get {
                return ResourceManager.GetString("CSVTXTWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source Selector Window.
        /// </summary>
        public static string DataSrcSelectorWinTitle {
            get {
                return ResourceManager.GetString("DataSrcSelectorWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete variable?.
        /// </summary>
        public static string DeleteVarConfirmation {
            get {
                return ResourceManager.GetString("DeleteVarConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this message again.
        /// </summary>
        public static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another column with same name exists. Please try another name..
        /// </summary>
        public static string DupColMsg {
            get {
                return ResourceManager.GetString("DupColMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Column Name.
        /// </summary>
        public static string DupColNameTitle {
            get {
                return ResourceManager.GetString("DupColNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter graphic image dimensions (in pixels) :.
        /// </summary>
        public static string EnterImgSizePrompt {
            get {
                return ResourceManager.GetString("EnterImgSizePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter model class name (case sensitive):.
        /// </summary>
        public static string EnterModelClassPrompt {
            get {
                return ResourceManager.GetString("EnterModelClassPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name(s) of one or more package(s).
        /// </summary>
        public static string EnterPkgNamesLine1 {
            get {
                return ResourceManager.GetString("EnterPkgNamesLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to separated by comma.(package names are case sensitive).
        /// </summary>
        public static string EnterPkgNamesLine2 {
            get {
                return ResourceManager.GetString("EnterPkgNamesLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Label.
        /// </summary>
        public static string ExistingLabel {
            get {
                return ResourceManager.GetString("ExistingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist!.
        /// </summary>
        public static string FileRecentRScriptNotFound {
            get {
                return ResourceManager.GetString("FileRecentRScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow search by selecting one or more columns:.
        /// </summary>
        public static string FindDatagridNarrowSearch {
            get {
                return ResourceManager.GetString("FindDatagridNarrowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Datagrid Window.
        /// </summary>
        public static string findDatagridTitle {
            get {
                return ResourceManager.GetString("findDatagridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Replace Window.
        /// </summary>
        public static string FindReplaceWinTitle {
            get {
                return ResourceManager.GetString("FindReplaceWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Variable Window.
        /// </summary>
        public static string FindVarGridWinTitle {
            get {
                return ResourceManager.GetString("FindVarGridWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Variable Name:.
        /// </summary>
        public static string FindVarName {
            get {
                return ResourceManager.GetString("FindVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find What:.
        /// </summary>
        public static string findwhat {
            get {
                return ResourceManager.GetString("findwhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating License Server Details:.
        /// </summary>
        public static string FLicGrpBox1Title {
            get {
                return ResourceManager.GetString("FLicGrpBox1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Information:.
        /// </summary>
        public static string FLicGrpBox2Title {
            get {
                return ResourceManager.GetString("FLicGrpBox2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed To:.
        /// </summary>
        public static string FLicGrpBox3Title {
            get {
                return ResourceManager.GetString("FLicGrpBox3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Navigation Tree.
        /// </summary>
        public static string HideNavTreeText {
            get {
                return ResourceManager.GetString("HideNavTreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryMenuName {
            get {
                return ResourceManager.GetString("HistoryMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default image height and width set to 600 pixels each..
        /// </summary>
        public static string ImgDefaultDimSetMsg {
            get {
                return ResourceManager.GetString("ImgDefaultDimSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default image dimensions set.
        /// </summary>
        public static string ImgDefaultDimSetMsgTitle {
            get {
                return ResourceManager.GetString("ImgDefaultDimSetMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Height:.
        /// </summary>
        public static string ImgHeight {
            get {
                return ResourceManager.GetString("ImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Width:.
        /// </summary>
        public static string ImgWidth {
            get {
                return ResourceManager.GetString("ImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In selected text.
        /// </summary>
        public static string InSelTextChkBox {
            get {
                return ResourceManager.GetString("InSelTextChkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview the dialog and sub dialogs associated with the command below.&quot; +&quot;Clicking on the Syntax button will bring up the syntax in the Command Editor. &quot;+ &quot;Clicking on the HELP button will bring up the Help. Clicking on the buttons in the dialog will bring up sub-dialogs. The property grid displays the properties of the dialog..
        /// </summary>
        public static string InspectHelpText {
            get {
                return ResourceManager.GetString("InspectHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect Dialog Window.
        /// </summary>
        public static string InspectWinTitle {
            get {
                return ResourceManager.GetString("InspectWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Packages From Folder.
        /// </summary>
        public static string InstallFromZipTitle {
            get {
                return ResourceManager.GetString("InstallFromZipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invalid date/time..
        /// </summary>
        public static string InvalidDateTimeMsg {
            get {
                return ResourceManager.GetString("InvalidDateTimeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date/Time..
        /// </summary>
        public static string InvalidDateTimeTitle {
            get {
                return ResourceManager.GetString("InvalidDateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not valid for variable of type Measure = Scale(Numeric).
        /// </summary>
        public static string InvalidOperationOnScale {
            get {
                return ResourceManager.GetString("InvalidOperationOnScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have generated an output table which has exceeded the configured threshold of {0} values..
        /// </summary>
        public static string LargeResultWarningMsg1 {
            get {
                return ResourceManager.GetString("LargeResultWarningMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This table will take a long time to render in the output..
        /// </summary>
        public static string LargeResultWarningMsg1b {
            get {
                return ResourceManager.GetString("LargeResultWarningMsg1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - To display the first {0} of a total {1} rows click \&quot;Display Partial Output\&quot;.
        /// </summary>
        public static string LargeResultWarningMsg2 {
            get {
                return ResourceManager.GetString("LargeResultWarningMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Click \&quot;Display Partial Output\&quot; to show partial results..
        /// </summary>
        public static string LargeResultWarningSecMsg2 {
            get {
                return ResourceManager.GetString("LargeResultWarningSecMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - To display the entire output click &quot;Display All Output&quot;..
        /// </summary>
        public static string LargeResultWarningWindowStmt1 {
            get {
                return ResourceManager.GetString("LargeResultWarningWindowStmt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - For very large output table you can also display text output which will be faster by printing the object directly from the BlueSky R Command Editor. Example: if SkyFormat(tableobj) is taking too long, type in tableobj in the BlueSky R Command Editor to get text output..
        /// </summary>
        public static string LargeResultWarningWindowStmt2 {
            get {
                return ResourceManager.GetString("LargeResultWarningWindowStmt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Click &quot;Cancel&quot; to abort table generation..
        /// </summary>
        public static string LargeResultWarningWindowStmt3 {
            get {
                return ResourceManager.GetString("LargeResultWarningWindowStmt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Packages (manually loaded by user from.
        /// </summary>
        public static string lbl1UserPkg {
            get {
                return ResourceManager.GetString("lbl1UserPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools &gt; Packages &gt; Load user session package(s) ).
        /// </summary>
        public static string lbl2UserPkg {
            get {
                return ResourceManager.GetString("lbl2UserPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Logging:.
        /// </summary>
        public static string lblAdvancedLogging {
            get {
                return ResourceManager.GetString("lblAdvancedLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name:.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While loading CSV/Excel files, convert &quot;character&quot; columns to &quot;factor&quot;..
        /// </summary>
        public static string lblCharToFactor {
            get {
                return ResourceManager.GetString("lblCharToFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns:.
        /// </summary>
        public static string lblColumns {
            get {
                return ResourceManager.GetString("lblColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Title Color:.
        /// </summary>
        public static string lblCommandTitleColor {
            get {
                return ResourceManager.GetString("lblCommandTitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string lblDataTab {
            get {
                return ResourceManager.GetString("lblDataTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default instance name for MSSQL Full is MSSQLSERVER and for MSSQL Express is SQLEXPRESS.
        /// </summary>
        public static string lblDefaultInstanceName {
            get {
                return ResourceManager.GetString("lblDefaultInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Packages (loads with application):.
        /// </summary>
        public static string lblDefPkg {
            get {
                return ResourceManager.GetString("lblDefPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Model classes that will appear in the &apos;Model Type&apos; dropdown..
        /// </summary>
        public static string lblDropdownModels {
            get {
                return ResourceManager.GetString("lblDropdownModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Color:.
        /// </summary>
        public static string lblErrorColor {
            get {
                return ResourceManager.GetString("lblErrorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: C:/Program Files/R/R-3.2.1 (use forward slash &apos;/&apos; for path).
        /// </summary>
        public static string lblExampleRHomeDir {
            get {
                return ResourceManager.GetString("lblExampleRHomeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: C:/Program Files/R/R-3.4.2.
        /// </summary>
        public static string lblExampleRHomeDir2 {
            get {
                return ResourceManager.GetString("lblExampleRHomeDir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string lblFind {
            get {
                return ResourceManager.GetString("lblFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Floating License Server&apos;s IP adress and port number(e.g. 127.0.0.1:16090):.
        /// </summary>
        public static string lblFLicEnterServerIP {
            get {
                return ResourceManager.GetString("lblFLicEnterServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in IP address and port number of the floating license server if you are using this application for the first time. If the license server in your organization has been moved/modified then enter new ip address and port number in the above field. Finally, click &apos;Connect to Server&apos; button after entering IP address and port number..
        /// </summary>
        public static string lblFLicEnterServerIPTip {
            get {
                return ResourceManager.GetString("lblFLicEnterServerIPTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expiration Date:.
        /// </summary>
        public static string lblFLicExpiryDate {
            get {
                return ResourceManager.GetString("lblFLicExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        public static string lblFLicOwnerCompany {
            get {
                return ResourceManager.GetString("lblFLicOwnerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string lblFLicOwnerEmail {
            get {
                return ResourceManager.GetString("lblFLicOwnerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string lblFLicOwnerName {
            get {
                return ResourceManager.GetString("lblFLicOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to license server for validating license. Please wait....
        /// </summary>
        public static string lblFLicServerConnectingPlzWait {
            get {
                return ResourceManager.GetString("lblFLicServerConnectingPlzWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Status:.
        /// </summary>
        public static string lblFLicStatus {
            get {
                return ResourceManager.GetString("lblFLicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Image Height:.
        /// </summary>
        public static string lblImageHeight {
            get {
                return ResourceManager.GetString("lblImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Image Width:.
        /// </summary>
        public static string lblImageWidth {
            get {
                return ResourceManager.GetString("lblImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Directory:.
        /// </summary>
        public static string lblInitialDirectory {
            get {
                return ResourceManager.GetString("lblInitialDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter server instance name :.
        /// </summary>
        public static string lblInstanceName {
            get {
                return ResourceManager.GetString("lblInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please modify the server instance name if its different from the default..
        /// </summary>
        public static string lblInstanceNameNote {
            get {
                return ResourceManager.GetString("lblInstanceNameNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comma separated list of days (how many days before expiry, reminder should notify you. Blank field loads defaults. Enter 0 or 1 if you dont want to set any days):.
        /// </summary>
        public static string lblLicNotifyDays {
            get {
                return ResourceManager.GetString("lblLicNotifyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load SAV file&apos;s missing values:.
        /// </summary>
        public static string lblLoadMissing {
            get {
                return ResourceManager.GetString("lblLoadMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level:.
        /// </summary>
        public static string lblLogLevel {
            get {
                return ResourceManager.GetString("lblLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string lblMatchCaseChkBox {
            get {
                return ResourceManager.GetString("lblMatchCaseChkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        public static string lblMatchOptions {
            get {
                return ResourceManager.GetString("lblMatchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. No. Of Chars in Left Tree:.
        /// </summary>
        public static string lblMaxCharsNavTree {
            get {
                return ResourceManager.GetString("lblMaxCharsNavTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter maximum number of factor you want:.
        /// </summary>
        public static string lblMaxFactor {
            get {
                return ResourceManager.GetString("lblMaxFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type:.
        /// </summary>
        public static string lblModelType {
            get {
                return ResourceManager.GetString("lblModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse hover box color (in output pane):.
        /// </summary>
        public static string lblMouseHoverBoxColor {
            get {
                return ResourceManager.GetString("lblMouseHoverBoxColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation tree selected item box color (in output pane):.
        /// </summary>
        public static string lblNavTreeSelColor {
            get {
                return ResourceManager.GetString("lblNavTreeSelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Decimal Digits:.
        /// </summary>
        public static string lblNoDecimalDigits {
            get {
                return ResourceManager.GetString("lblNoDecimalDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Options window when opening dataset:.
        /// </summary>
        public static string lblOpenOptions {
            get {
                return ResourceManager.GetString("lblOpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size:.
        /// </summary>
        public static string lblPageSize {
            get {
                return ResourceManager.GetString("lblPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size:.
        /// </summary>
        public static string lblPDFFontSize {
            get {
                return ResourceManager.GetString("lblPDFFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comma separated margin values (Left, Top, Right, Bottom):.
        /// </summary>
        public static string lblPDFMargins {
            get {
                return ResourceManager.GetString("lblPDFMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter maximum number of table columns per page(including row header columns):.
        /// </summary>
        public static string lblPDFMaxCols {
            get {
                return ResourceManager.GetString("lblPDFMaxCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter maximum number of table rows per page(including column header rows):.
        /// </summary>
        public static string lblPDFMaxRows {
            get {
                return ResourceManager.GetString("lblPDFMaxRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Model:.
        /// </summary>
        public static string lblPickModel {
            get {
                return ResourceManager.GetString("lblPickModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace With:.
        /// </summary>
        public static string lblReplaceWith {
            get {
                return ResourceManager.GetString("lblReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain scientific notation for a very small number (eg.0.00001234, 1.234e-5, -0.00001234, -1.234e-5)..
        /// </summary>
        public static string lblRetainSciNotation {
            get {
                return ResourceManager.GetString("lblRetainSciNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Home Directory:.
        /// </summary>
        public static string lblRHomeDir {
            get {
                return ResourceManager.GetString("lblRHomeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Syntax Color:.
        /// </summary>
        public static string lblRSynColor {
            get {
                return ResourceManager.GetString("lblRSynColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a database:.
        /// </summary>
        public static string lblSelDatabase {
            get {
                return ResourceManager.GetString("lblSelDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Tables/Views to see the list of Tables/Views. Click on the table/view name to see its columns on the right pane.
        /// </summary>
        public static string lblSelTableView {
            get {
                return ResourceManager.GetString("lblSelTableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The R object that contains the results of the analytical function may contain numeric row headers. This option determine whether the row headers are displayed or hidden. When checked, numeric row headers are shown in output grid:.
        /// </summary>
        public static string lblShowHideNumericHeaders {
            get {
                return ResourceManager.GetString("lblShowHideNumericHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the columns of the selected table..
        /// </summary>
        public static string lblShowsCols {
            get {
                return ResourceManager.GetString("lblShowsCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Connection Parameters:.
        /// </summary>
        public static string lblSQLConnectionParams {
            get {
                return ResourceManager.GetString("lblSQLConnectionParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name:.
        /// </summary>
        public static string lblSQLDatabaseName {
            get {
                return ResourceManager.GetString("lblSQLDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. MS-SQL Example:         SELECT * FROM Owner.TABLE-NAME.
        /// </summary>
        public static string lblSQLExample1 {
            get {
                return ResourceManager.GetString("lblSQLExample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. MySQL / Postgres / MS-ACCESS Example:       SELECT * FROM TABLE-NAME.
        /// </summary>
        public static string lblSQLExample2 {
            get {
                return ResourceManager.GetString("lblSQLExample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host / Server:.
        /// </summary>
        public static string lblSQLHostServer {
            get {
                return ResourceManager.GetString("lblSQLHostServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string lblSQLPassword {
            get {
                return ResourceManager.GetString("lblSQLPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Data Source:.
        /// </summary>
        public static string lblSQLSelDataSrc {
            get {
                return ResourceManager.GetString("lblSQLSelDataSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your &apos;SELECT&apos; query in the textbox below. You can enter complex queries, sub-queries, joins as supported by your SQL server..
        /// </summary>
        public static string lblSQLtip {
            get {
                return ResourceManager.GetString("lblSQLtip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID:.
        /// </summary>
        public static string lblSQLUserID {
            get {
                return ResourceManager.GetString("lblSQLUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables/Views:.
        /// </summary>
        public static string lblTableView {
            get {
                return ResourceManager.GetString("lblTableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Folder:.
        /// </summary>
        public static string lblTempFolder {
            get {
                return ResourceManager.GetString("lblTempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold number of values per output table for which warning will be displayed informing the user that table generation will be time consuming and giving the user the choice to display the partial results..
        /// </summary>
        public static string lblThresholdCount {
            get {
                return ResourceManager.GetString("lblThresholdCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micosoft SQL server Driver path:.
        /// </summary>
        public static string lblTitleDriverPath {
            get {
                return ResourceManager.GetString("lblTitleDriverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: C:/Program Files/Microsoft SQL Server JDBC Driver 3.0/sqljdbc_3.0/enu/sqljdbc4.jar.
        /// </summary>
        public static string lblTitleDriverPathExample {
            get {
                return ResourceManager.GetString("lblTitleDriverPathExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: You must use forward slash(/) in path..
        /// </summary>
        public static string lblTitleDriverPathNote {
            get {
                return ResourceManager.GetString("lblTitleDriverPathNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSSQL Server Instance:.
        /// </summary>
        public static string lblTitleServerInstance {
            get {
                return ResourceManager.GetString("lblTitleServerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on the row to access functions, for eg. Add Factor Level, Change Label, Make Factor, Insert New Variable and Delete Variable.
        /// </summary>
        public static string lblVarGridContext {
            get {
                return ResourceManager.GetString("lblVarGridContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string lblVariablesTab {
            get {
                return ResourceManager.GetString("lblVariablesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Word.
        /// </summary>
        public static string lblWholeWordChkBox {
            get {
                return ResourceManager.GetString("lblWholeWordChkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Browse&apos; and locate your folder that contains R package zip files..
        /// </summary>
        public static string LocateZipMsg {
            get {
                return ResourceManager.GetString("LocateZipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached end. No more matches..
        /// </summary>
        public static string MatchEndReached {
            get {
                return ResourceManager.GetString("MatchEndReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Target(as a Sibling).
        /// </summary>
        public static string MenuAboveBelowDialogOption1 {
            get {
                return ResourceManager.GetString("MenuAboveBelowDialogOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Target(as a Sibling).
        /// </summary>
        public static string MenuAboveBelowDialogOption2 {
            get {
                return ResourceManager.GetString("MenuAboveBelowDialogOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside Target(as a Child).
        /// </summary>
        public static string MenuAboveBelowDialogOption3 {
            get {
                return ResourceManager.GetString("MenuAboveBelowDialogOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where in target would you like to place your dragged item?.
        /// </summary>
        public static string MenuAboveBelowDialogPrompt {
            get {
                return ResourceManager.GetString("MenuAboveBelowDialogPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragged Item Location Dialog..
        /// </summary>
        public static string MenuAboveBelowDialogTitle {
            get {
                return ResourceManager.GetString("MenuAboveBelowDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        public static string menuCloseWindow {
            get {
                return ResourceManager.GetString("menuCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus can&apos;t be generated....
        /// </summary>
        public static string MenuGenerationFailedMsg {
            get {
                return ResourceManager.GetString("MenuGenerationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string menuOpen {
            get {
                return ResourceManager.GetString("menuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuOutputEdit {
            get {
                return ResourceManager.GetString("MenuOutputEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MenuOutputEditCopy {
            get {
                return ResourceManager.GetString("MenuOutputEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string MenuOutputEditCut {
            get {
                return ResourceManager.GetString("MenuOutputEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string MenuOutputEditPaste {
            get {
                return ResourceManager.GetString("MenuOutputEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string MenuOutputEditRedo {
            get {
                return ResourceManager.GetString("MenuOutputEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string MenuOutputEditUndo {
            get {
                return ResourceManager.GetString("MenuOutputEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuOutputFile {
            get {
                return ResourceManager.GetString("MenuOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        public static string MenuOutputFileClose {
            get {
                return ResourceManager.GetString("MenuOutputFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open BlueSky Saved Output.
        /// </summary>
        public static string MenuOutputFileOpenOutput {
            get {
                return ResourceManager.GetString("MenuOutputFileOpenOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string MenuOutputFileSaveAs {
            get {
                return ResourceManager.GetString("MenuOutputFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As PDF.
        /// </summary>
        public static string MenuOutputFileSaveAsPDF {
            get {
                return ResourceManager.GetString("MenuOutputFileSaveAsPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size.
        /// </summary>
        public static string MenuOutputImageSize {
            get {
                return ResourceManager.GetString("MenuOutputImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Graphic Size.
        /// </summary>
        public static string MenuOutputImageSizeChange {
            get {
                return ResourceManager.GetString("MenuOutputImageSizeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default Graphic Size.
        /// </summary>
        public static string MenuOutputImageSizeDefault {
            get {
                return ResourceManager.GetString("MenuOutputImageSizeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string MenuOutputLayout {
            get {
                return ResourceManager.GetString("MenuOutputLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string MenuOutputLayoutHorizontal {
            get {
                return ResourceManager.GetString("MenuOutputLayoutHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Navigation Tree.
        /// </summary>
        public static string MenuOutputLayoutShowNavTree {
            get {
                return ResourceManager.GetString("MenuOutputLayoutShowNavTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string MenuOutputLayoutVertical {
            get {
                return ResourceManager.GetString("MenuOutputLayoutVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MenuSynEdit {
            get {
                return ResourceManager.GetString("MenuSynEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string MenuSynEditCopy {
            get {
                return ResourceManager.GetString("MenuSynEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string MenuSynEditCut {
            get {
                return ResourceManager.GetString("MenuSynEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find/Replace.
        /// </summary>
        public static string MenuSynEditFindReplace {
            get {
                return ResourceManager.GetString("MenuSynEditFindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string MenuSynEditPaste {
            get {
                return ResourceManager.GetString("MenuSynEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string MenuSynEditRedo {
            get {
                return ResourceManager.GetString("MenuSynEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string MenuSynEditUndo {
            get {
                return ResourceManager.GetString("MenuSynEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuSynFile {
            get {
                return ResourceManager.GetString("MenuSynFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MenuSynFileNew {
            get {
                return ResourceManager.GetString("MenuSynFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MenuSynFileOpen {
            get {
                return ResourceManager.GetString("MenuSynFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string MenuSynFileRecent {
            get {
                return ResourceManager.GetString("MenuSynFileRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuSynFileSave {
            get {
                return ResourceManager.GetString("MenuSynFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As.
        /// </summary>
        public static string MenuSynFileSaveAs {
            get {
                return ResourceManager.GetString("MenuSynFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: type lm without quotes and click &apos;Add Class&apos;.
        /// </summary>
        public static string ModelClassExample {
            get {
                return ResourceManager.GetString("ModelClassExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Unselect this node to show/hide in right pane.
        /// </summary>
        public static string NavTreeCheckboxTooltip {
            get {
                return ResourceManager.GetString("NavTreeCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to bring the item in the view.
        /// </summary>
        public static string NavTreeNodeTBTooltip {
            get {
                return ResourceManager.GetString("NavTreeNodeTBTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Label.
        /// </summary>
        public static string NewLabel {
            get {
                return ResourceManager.GetString("NewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Match.
        /// </summary>
        public static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found.
        /// </summary>
        public static string NoMatchFound {
            get {
                return ResourceManager.GetString("NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more matches.
        /// </summary>
        public static string NoMoreMatch {
            get {
                return ResourceManager.GetString("NoMoreMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value, you have entered a non-numeric value for a numeric variable. If you want to enter a non-numeric values make this variable a factor and enter non-numeric levels.
        /// </summary>
        public static string NonNumForNumVar {
            get {
                return ResourceManager.GetString("NonNumForNumVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: All the files in the folder must be R package .zip files..
        /// </summary>
        public static string NoteMsg {
            get {
                return ResourceManager.GetString("NoteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric levels.
        /// </summary>
        public static string NumericLevels {
            get {
                return ResourceManager.GetString("NumericLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of Analysis.
        /// </summary>
        public static string OutputPanelTitle {
            get {
                return ResourceManager.GetString("OutputPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OutputViewerOptionsMenu {
            get {
                return ResourceManager.GetString("OutputViewerOptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueSky Output Viewer.
        /// </summary>
        public static string OutputViewerTitle {
            get {
                return ResourceManager.GetString("OutputViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouput and Syntax Window-.
        /// </summary>
        public static string OutputWindowMainTitle {
            get {
                return ResourceManager.GetString("OutputWindowMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Active).
        /// </summary>
        public static string OutputWindowTitleStatus {
            get {
                return ResourceManager.GetString("OutputWindowTitleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the output of the analysis?.
        /// </summary>
        public static string OutputWinSavePromptPart1 {
            get {
                return ResourceManager.GetString("OutputWinSavePromptPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes : Save all and Close.
        /// </summary>
        public static string OutputWinSavePromptPart2 {
            get {
                return ResourceManager.GetString("OutputWinSavePromptPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No : Close without saving..
        /// </summary>
        public static string OutputWinSavePromptPart3 {
            get {
                return ResourceManager.GetString("OutputWinSavePromptPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Output?.
        /// </summary>
        public static string OutputWinSavePromptTitle {
            get {
                return ResourceManager.GetString("OutputWinSavePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection in progress. Please wait.....
        /// </summary>
        public static string PlzWaitSQL {
            get {
                return ResourceManager.GetString("PlzWaitSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening RData file.
        /// </summary>
        public static string RDataWarningTitle {
            get {
                return ResourceManager.GetString("RDataWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found!.
        /// </summary>
        public static string RecentScriptNotFoundMsgBoxTitle {
            get {
                return ResourceManager.GetString("RecentScriptNotFoundMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.xml not found....
        /// </summary>
        public static string RecentXMLnotfound {
            get {
                return ResourceManager.GetString("RecentXMLnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the R syntax?.
        /// </summary>
        public static string REditorCloseSaveScriptPrompt {
            get {
                return ResourceManager.GetString("REditorCloseSaveScriptPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only .r (R script) and .txt(plain text) files are supported..
        /// </summary>
        public static string REditorFileTypeSupportedMsg {
            get {
                return ResourceManager.GetString("REditorFileTypeSupportedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of text: No more occurrences. Search pointer will start from the begining..
        /// </summary>
        public static string REditorFindNextEndsMsg {
            get {
                return ResourceManager.GetString("REditorFindNextEndsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more match.
        /// </summary>
        public static string REditorFindNextEndsMsgbxTitle {
            get {
                return ResourceManager.GetString("REditorFindNextEndsMsgbxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some text in R Command Editor first.
        /// </summary>
        public static string REditorReplaceAllInSelectedMsg {
            get {
                return ResourceManager.GetString("REditorReplaceAllInSelectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Selected.
        /// </summary>
        public static string REditorReplaceAllInSelectedMsgboxTitle {
            get {
                return ResourceManager.GetString("REditorReplaceAllInSelectedMsgboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close current command script?.
        /// </summary>
        public static string REditorSavePromptMsgBoxTitle {
            get {
                return ResourceManager.GetString("REditorSavePromptMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save current script?.
        /// </summary>
        public static string REditorSaveScriptPrompt {
            get {
                return ResourceManager.GetString("REditorSaveScriptPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Home Directory:.
        /// </summary>
        public static string RHomeDirLabel {
            get {
                return ResourceManager.GetString("RHomeDirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSky R scripts,.
        /// </summary>
        public static string RScriptFilenameFilter {
            get {
                return ResourceManager.GetString("RScriptFilenameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Current Dataset.
        /// </summary>
        public static string ScoringSectionTitle {
            get {
                return ResourceManager.GetString("ScoringSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more R data.frame object(s) to load them in the UI data grid:.
        /// </summary>
        public static string SelDataframeToLoad {
            get {
                return ResourceManager.GetString("SelDataframeToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more packages:.
        /// </summary>
        public static string SelOneOrMore {
            get {
                return ResourceManager.GetString("SelOneOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( Tip: Use Ctrl or Shift key for multi-select.).
        /// </summary>
        public static string SelOneOrMoreTip {
            get {
                return ResourceManager.GetString("SelOneOrMoreTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Packages Window.
        /// </summary>
        public static string SelPkgWinTitle {
            get {
                return ResourceManager.GetString("SelPkgWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select One Table/Sheet.
        /// </summary>
        public static string SelTableOrSheet {
            get {
                return ResourceManager.GetString("SelTableOrSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Worksheet Window.
        /// </summary>
        public static string SelWorksheetWin {
            get {
                return ResourceManager.GetString("SelWorksheetWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make corrections to the &apos;R Home Directory&apos; path if incorrect and then relaunch the app. (IMPORTANT: Use forward slash as a path separator as shown in the example below)..
        /// </summary>
        public static string SetRHomeLabelTextAtLaunchFail {
            get {
                return ResourceManager.GetString("SetRHomeLabelTextAtLaunchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide R Command Editor Panel.
        /// </summary>
        public static string ShowHideSyntaxPanel {
            get {
                return ResourceManager.GetString("ShowHideSyntaxPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Navigation Tree.
        /// </summary>
        public static string ShowNavTreeText {
            get {
                return ResourceManager.GetString("ShowNavTreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show output tables in APA(American Psychological Association) style..
        /// </summary>
        public static string ShowOutputInAPA {
            get {
                return ResourceManager.GetString("ShowOutputInAPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show warning message box when RData file is opened..
        /// </summary>
        public static string ShowRDataWarningMessage {
            get {
                return ResourceManager.GetString("ShowRDataWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table and Column(s) Selector Window.
        /// </summary>
        public static string SQLSelTableWinTitle {
            get {
                return ResourceManager.GetString("SQLSelTableWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For details, go to Help -&gt; Licensing)..
        /// </summary>
        public static string StatusbarLicInfo {
            get {
                return ResourceManager.GetString("StatusbarLicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split on :.
        /// </summary>
        public static string StatusbarSplitInfo {
            get {
                return ResourceManager.GetString("StatusbarSplitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Syntax generated by dialog.
        /// </summary>
        public static string syncomment {
            get {
                return ResourceManager.GetString("syncomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #There is no syntax associated with dialog.
        /// </summary>
        public static string syncomment2 {
            get {
                return ResourceManager.GetString("syncomment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### This is R syntax editor ###.
        /// </summary>
        public static string SynGetStrtMsg1 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### You can enter some R statements here and execute them..
        /// </summary>
        public static string SynGetStrtMsg2 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Type in few R statements..
        /// </summary>
        public static string SynGetStrtMsg3 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Select one or more, complete R statements..
        /// </summary>
        public static string SynGetStrtMsg4 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Click Run (blue triangle icon) from the toolbar above..
        /// </summary>
        public static string SynGetStrtMsg5 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### See the generated output on the output panel(on the left)..
        /// </summary>
        public static string SynGetStrtMsg6 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyntaxRecent.xml not found..
        /// </summary>
        public static string SynRecentXmlNotFound {
            get {
                return ResourceManager.GetString("SynRecentXmlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string TabTitleAdvanced {
            get {
                return ResourceManager.GetString("TabTitleAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string TabTitleColors {
            get {
                return ResourceManager.GetString("TabTitleColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Packages.
        /// </summary>
        public static string TabTitleDefaultPackages {
            get {
                return ResourceManager.GetString("TabTitleDefaultPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string TabTitleImage {
            get {
                return ResourceManager.GetString("TabTitleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string TabTitleModels {
            get {
                return ResourceManager.GetString("TabTitleModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string TabTitleOthers {
            get {
                return ResourceManager.GetString("TabTitleOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Settings.
        /// </summary>
        public static string TabTitlePathSettings {
            get {
                return ResourceManager.GetString("TabTitlePathSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Settings.
        /// </summary>
        public static string TabTitlePDFSettings {
            get {
                return ResourceManager.GetString("TabTitlePDFSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Settings.
        /// </summary>
        public static string TabTitleSQLSettings {
            get {
                return ResourceManager.GetString("TabTitleSQLSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Packages.
        /// </summary>
        public static string TabTitleUserPackages {
            get {
                return ResourceManager.GetString("TabTitleUserPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this dataset.
        /// </summary>
        public static string ToolTipCloseDataset {
            get {
                return ResourceManager.GetString("ToolTipCloseDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted.
        /// </summary>
        public static string ToolTipSorted {
            get {
                return ResourceManager.GetString("ToolTipSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Level Warning:.
        /// </summary>
        public static string WarningAddRemoveLabel {
            get {
                return ResourceManager.GetString("WarningAddRemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Level Warning:.
        /// </summary>
        public static string WarningChangeLevel {
            get {
                return ResourceManager.GetString("WarningChangeLevel", resourceCulture);
            }
        }
    }
}
