//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSky.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueSky.Properties.NoResources", typeof(NoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA.
        /// </summary>
        public static string AAA {
            get {
                return ResourceManager.GetString("AAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All floating licenses in use..
        /// </summary>
        public static string AllFloatingLicInUse {
            get {
                return ResourceManager.GetString("AllFloatingLicInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueSky is downloading and installing required R packages..
        /// </summary>
        public static string BSkyDownloadingReqPkgs {
            get {
                return ResourceManager.GetString("BSkyDownloadingReqPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array, matrix dataframe and BSky return structure..
        /// </summary>
        public static string BSkyFormatSupportedTypes {
            get {
                return ResourceManager.GetString("BSkyFormatSupportedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;bskygrphcntrlimage&apos; not found in config file. Aborting....
        /// </summary>
        public static string bskygrphctrlimgConfigKeyNotFound {
            get {
                return ResourceManager.GetString("bskygrphctrlimgConfigKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueSky application needs following R package(s):.
        /// </summary>
        public static string BSkyNeedsRPkgs {
            get {
                return ResourceManager.GetString("BSkyNeedsRPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueSky application may not work properly if the required R packages are missing..
        /// </summary>
        public static string BSkyNotWorkReqPkgMissing {
            get {
                return ResourceManager.GetString("BSkyNotWorkReqPkgMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueSky package missing.
        /// </summary>
        public static string BSkyPkgMissing {
            get {
                return ResourceManager.GetString("BSkyPkgMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Object cannot be formatted using BSKyFormat. BSkyFormat can be used on Array, Matrix, Data Frame and BSky List objects only.
        /// </summary>
        public static string CantBSkyFormatErrorMsg {
            get {
                return ResourceManager.GetString("CantBSkyFormatErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create template from.
        /// </summary>
        public static string CantCreateTemplate {
            get {
                return ResourceManager.GetString("CantCreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t Execute the command.
        /// </summary>
        public static string CantExecuteCommand {
            get {
                return ResourceManager.GetString("CantExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t install Dialog.
        /// </summary>
        public static string CantInstallDialog {
            get {
                return ResourceManager.GetString("CantInstallDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog cannot be installed as output file is not mentioned.
        /// </summary>
        public static string CantInstallDialogNoOutFile {
            get {
                return ResourceManager.GetString("CantInstallDialogNoOutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty, Exiting Dialog install.
        /// </summary>
        public static string CantInstallDialogNoTitle {
            get {
                return ResourceManager.GetString("CantInstallDialogNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t Launch BlueSky Application!.
        /// </summary>
        public static string CantLaunchBSkyApp {
            get {
                return ResourceManager.GetString("CantLaunchBSkyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open.
        /// </summary>
        public static string cantopen {
            get {
                return ResourceManager.GetString("cantopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the file.
        /// </summary>
        public static string CantOpenFile {
            get {
                return ResourceManager.GetString("CantOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Open Command Editor. UAMenuCommand properties not set..
        /// </summary>
        public static string CantOpenREditor {
            get {
                return ResourceManager.GetString("CantOpenREditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be saved to &apos;.XLS&apos; format. Click OK to choose a different format like XLSX, RData etc..
        /// </summary>
        public static string CantSaveAsExcel {
            get {
                return ResourceManager.GetString("CantSaveAsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close.
        /// </summary>
        public static string CloseConfirmation {
            get {
                return ResourceManager.GetString("CloseConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close Dataset?.
        /// </summary>
        public static string CloseDatasetConfirmation {
            get {
                return ResourceManager.GetString("CloseDatasetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue to install dialog?.
        /// </summary>
        public static string ConfirmDialogInstall {
            get {
                return ResourceManager.GetString("ConfirmDialogInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite the command.
        /// </summary>
        public static string ConfirmDialogOverwrite {
            get {
                return ResourceManager.GetString("ConfirmDialogOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reach License Server.(Go to [ Help -&gt; Licensing ] and connect to the current floating license server)..
        /// </summary>
        public static string ConnectCurrFloatingServer {
            get {
                return ResourceManager.GetString("ConnectCurrFloatingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your administrator..
        /// </summary>
        public static string ContactAdmin {
            get {
                return ResourceManager.GetString("ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error Occurred!.
        /// </summary>
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset?.
        /// </summary>
        public static string dataset {
            get {
                return ResourceManager.GetString("dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been set to NULL. The reason may be, running some analysis or command on the dataset..
        /// </summary>
        public static string DatasetBecameNull {
            get {
                return ResourceManager.GetString("DatasetBecameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL Dataset..
        /// </summary>
        public static string DatasetNull {
            get {
                return ResourceManager.GetString("DatasetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Dataset object does not exist..
        /// </summary>
        public static string DatasetObjNotExists {
            get {
                return ResourceManager.GetString("DatasetObjNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Dataframe does not exist (or is NULL or has no rows/columns).
        /// </summary>
        public static string DFNotExists {
            get {
                return ResourceManager.GetString("DFNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog installed..
        /// </summary>
        public static string DialogInstalled {
            get {
                return ResourceManager.GetString("DialogInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Title Empty..
        /// </summary>
        public static string DialogTitleEmpty {
            get {
                return ResourceManager.GetString("DialogTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to needs the following R package(s):.
        /// </summary>
        public static string DlgNeedTheseRPkgs {
            get {
                return ResourceManager.GetString("DlgNeedTheseRPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist..
        /// </summary>
        public static string DoesNotExist {
            get {
                return ResourceManager.GetString("DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter package name that you want to load..
        /// </summary>
        public static string EnterPkgNameToLoad {
            get {
                return ResourceManager.GetString("EnterPkgNameToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot Load/Refresh Dataset.
        /// </summary>
        public static string ErrCantLodRefDataset {
            get {
                return ResourceManager.GetString("ErrCantLodRefDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in block declaration. Mismatch { or }.
        /// </summary>
        public static string ErrCurlyMismatch {
            get {
                return ResourceManager.GetString("ErrCurlyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing the command..
        /// </summary>
        public static string ErrExecutingCommand {
            get {
                return ResourceManager.GetString("ErrExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Getting Installed Packages.
        /// </summary>
        public static string ErrGettingInstalledPkgs {
            get {
                return ResourceManager.GetString("ErrGettingInstalledPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting installed packages..
        /// </summary>
        public static string ErrGettingInstalledPkgs2 {
            get {
                return ResourceManager.GetString("ErrGettingInstalledPkgs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Getting Loaded Packages.
        /// </summary>
        public static string ErrGettingLoadedPkgs {
            get {
                return ResourceManager.GetString("ErrGettingLoadedPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting loaded packages..
        /// </summary>
        public static string ErrGettingLoadedPkgs2 {
            get {
                return ResourceManager.GetString("ErrGettingLoadedPkgs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Command Error.
        /// </summary>
        public static string ErrInRCommand {
            get {
                return ResourceManager.GetString("ErrInRCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Installing CRAN Package.
        /// </summary>
        public static string ErrInstallingFromCRAN {
            get {
                return ResourceManager.GetString("ErrInstallingFromCRAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Installing Package.
        /// </summary>
        public static string ErrInstallingRPkg {
            get {
                return ResourceManager.GetString("ErrInstallingRPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while installing package..
        /// </summary>
        public static string ErrInstallingRPkg2 {
            get {
                return ResourceManager.GetString("ErrInstallingRPkg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while installing required packages from CRAN..
        /// </summary>
        public static string ErrInstallReqPkgFrmCRAN {
            get {
                return ResourceManager.GetString("ErrInstallReqPkgFrmCRAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading new dataset. Make sure you have BlueSky R package installed.
        /// </summary>
        public static string ErrLoadingNewDS {
            get {
                return ResourceManager.GetString("ErrLoadingNewDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading following R package(s):.
        /// </summary>
        public static string ErrLoadingRPkg {
            get {
                return ResourceManager.GetString("ErrLoadingRPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading package..
        /// </summary>
        public static string ErrLoadingRPkg2 {
            get {
                return ResourceManager.GetString("ErrLoadingRPkg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Package(s).
        /// </summary>
        public static string ErrLoadingRPkgs {
            get {
                return ResourceManager.GetString("ErrLoadingRPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading User Session Package..
        /// </summary>
        public static string ErrLoadingUsrSessionPkg {
            get {
                return ResourceManager.GetString("ErrLoadingUsrSessionPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading user session package(s)..
        /// </summary>
        public static string ErrLoadingUsrSessionPkgs {
            get {
                return ResourceManager.GetString("ErrLoadingUsrSessionPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while modifying menu..
        /// </summary>
        public static string ErrModifyingMenu {
            get {
                return ResourceManager.GetString("ErrModifyingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a valid license to run this application. For help, go to Help -&gt; Licensing..
        /// </summary>
        public static string ErrNoValidNodeLic {
            get {
                return ResourceManager.GetString("ErrNoValidNodeLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Opening Dataset.
        /// </summary>
        public static string ErrOpeningDataset {
            get {
                return ResourceManager.GetString("ErrOpeningDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Opening Dataset.(probably not a data frame).
        /// </summary>
        public static string ErrOpeningDataset2 {
            get {
                return ResourceManager.GetString("ErrOpeningDataset2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the file.
        /// </summary>
        public static string ErrOpeningFile {
            get {
                return ResourceManager.GetString("ErrOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening registered graphic command list..
        /// </summary>
        public static string ErrOpeningRegGrpLst {
            get {
                return ResourceManager.GetString("ErrOpeningRegGrpLst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred!.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in block declaration. Mismatch ( or ).
        /// </summary>
        public static string ErrParenthesisMismatch {
            get {
                return ResourceManager.GetString("ErrParenthesisMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Required Model type not selected.
        /// </summary>
        public static string ErrReqModelNotSelected {
            get {
                return ResourceManager.GetString("ErrReqModelNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Required R Package(s) Missing.
        /// </summary>
        public static string ErrReqRPkgMissing {
            get {
                return ResourceManager.GetString("ErrReqRPkgMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Uninstalling Package.
        /// </summary>
        public static string ErrUninstallingPkg {
            get {
                return ResourceManager.GetString("ErrUninstallingPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uninstalling package..
        /// </summary>
        public static string ErrUninstallingPkg2 {
            get {
                return ResourceManager.GetString("ErrUninstallingPkg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Unloading Package.
        /// </summary>
        public static string ErrUnloadingPkg {
            get {
                return ResourceManager.GetString("ErrUnloadingPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while unloading package..
        /// </summary>
        public static string ErrUnloadingPkg2 {
            get {
                return ResourceManager.GetString("ErrUnloadingPkg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All floating licenses in use. (Please contact your administrator).
        /// </summary>
        public static string FloatingAllinUseMsg {
            get {
                return ResourceManager.GetString("FloatingAllinUseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to [ Help -&gt; Licensing ] to check the license status or to change the Floating License Server&apos;s IP address and port..
        /// </summary>
        public static string FloatingFixIPPortMsg {
            get {
                return ResourceManager.GetString("FloatingFixIPPortMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating License Error.
        /// </summary>
        public static string FloatingLicError {
            get {
                return ResourceManager.GetString("FloatingLicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating License Valid.
        /// </summary>
        public static string FloatingLicValid {
            get {
                return ResourceManager.GetString("FloatingLicValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to [ Help -&gt; Licensing ]  if server IP address and port are not set (or incorrectly set).
        /// </summary>
        public static string FloatingPortIncorrectlySet {
            get {
                return ResourceManager.GetString("FloatingPortIncorrectlySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Floating License Server Unreachable..
        /// </summary>
        public static string FloatingServerUnreachable {
            get {
                return ResourceManager.GetString("FloatingServerUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating License Server Unreachable..
        /// </summary>
        public static string FloatingServerUnreachable2 {
            get {
                return ResourceManager.GetString("FloatingServerUnreachable2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Format not supported..
        /// </summary>
        public static string FormatNotSupported {
            get {
                return ResourceManager.GetString("FormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. File format not supported (or corrupt file or duplicate column names)..
        /// </summary>
        public static string FormatNotSupported2 {
            get {
                return ResourceManager.GetString("FormatNotSupported2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model type and model is not specified OR you have selected invalid model type and model.
        /// </summary>
        public static string IncorrectModelOrModelType {
            get {
                return ResourceManager.GetString("IncorrectModelOrModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install the above mentioned R package(s)..
        /// </summary>
        public static string InstallAbvMentionedRPkgs {
            get {
                return ResourceManager.GetString("InstallAbvMentionedRPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed.
        /// </summary>
        public static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package(s) from CRAN.
        /// </summary>
        public static string InstallingFromCRAN {
            get {
                return ResourceManager.GetString("InstallingFromCRAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing required R packages from local drive.
        /// </summary>
        public static string InstallingRPkgFromLocal {
            get {
                return ResourceManager.GetString("InstallingRPkgFromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install New Dialog?.
        /// </summary>
        public static string InstallNewDialog {
            get {
                return ResourceManager.GetString("InstallNewDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Package.
        /// </summary>
        public static string InstallPkg {
            get {
                return ResourceManager.GetString("InstallPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Package From CRAN.
        /// </summary>
        public static string InstallPkgsFromCRAN {
            get {
                return ResourceManager.GetString("InstallPkgsFromCRAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install required R packages from CRAN by clicking:.
        /// </summary>
        public static string InstallReqRPkgFrmCRAN {
            get {
                return ResourceManager.GetString("InstallReqRPkgFrmCRAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing required R packages from CRAN.
        /// </summary>
        public static string InstallReqRPkgFrmCRAN2 {
            get {
                return ResourceManager.GetString("InstallReqRPkgFrmCRAN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install missing R package(s) and execute the dialog again..
        /// </summary>
        public static string InstallRPkgRunDialogAgain {
            get {
                return ResourceManager.GetString("InstallRPkgRunDialogAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to: Tools -&gt; Package -&gt; Install/Update package(s) from CRAN..
        /// </summary>
        public static string InstallUpdatePkgMenuPath {
            get {
                return ResourceManager.GetString("InstallUpdatePkgMenuPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error: Operation Failed.
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Directory path!.
        /// </summary>
        public static string invalidDir {
            get {
                return ResourceManager.GetString("invalidDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Filename!.
        /// </summary>
        public static string invalidFilename {
            get {
                return ResourceManager.GetString("invalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Path..
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not valid.
        /// </summary>
        public static string InvalidPath2 {
            get {
                return ResourceManager.GetString("InvalidPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is null..
        /// </summary>
        public static string isNull {
            get {
                return ResourceManager.GetString("isNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Package.
        /// </summary>
        public static string LoadLibrary {
            get {
                return ResourceManager.GetString("LoadLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Package(s).
        /// </summary>
        public static string LoadPackages {
            get {
                return ResourceManager.GetString("LoadPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Binary compatibility between BlueSky Statistics and R. 64bit BlueSky Statistics requires 64bit R and 32bit BlueSky Statistics requires 32bit R. (To find about BlueSky version : Go to &apos;Help &gt; About&apos; in BlueSky Statistics. To find about R version: Launch R GUI (Start &gt; run &gt; RGUI.exe) and execute R.version command on the console)..
        /// </summary>
        public static string MakeSure32x64Compatibility {
            get {
                return ResourceManager.GetString("MakeSure32x64Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Another session of the BlueSky application is not already running..
        /// </summary>
        public static string MakeSureAnotherBSkySession {
            get {
                return ResourceManager.GetString("MakeSureAnotherBSkySession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. R_HOME environment variable is pointing to the latest version of R..
        /// </summary>
        public static string MakeSureRHOME2LatestR {
            get {
                return ResourceManager.GetString("MakeSureRHOME2LatestR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. R is installed. BlueSky Statistics requires R. To download R visit: (http://cran.r-project.org).
        /// </summary>
        public static string MakeSureRInstalled {
            get {
                return ResourceManager.GetString("MakeSureRInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It may take 15 to 30 minutes to finish depending on your internet connection..
        /// </summary>
        public static string MayTake1530Min {
            get {
                return ResourceManager.GetString("MayTake1530Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing R Package(s).
        /// </summary>
        public static string MisingRPkgs {
            get {
                return ResourceManager.GetString("MisingRPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing.
        /// </summary>
        public static string missing {
            get {
                return ResourceManager.GetString("missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following model types are supported:.
        /// </summary>
        public static string ModelsSupportedAre {
            get {
                return ResourceManager.GetString("ModelsSupportedAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command to execute.
        /// </summary>
        public static string NoCommToExecute {
            get {
                return ResourceManager.GetString("NoCommToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Dataframe does not have row(s) or column(s)..
        /// </summary>
        public static string NoRowsColsPresent {
            get {
                return ResourceManager.GetString("NoRowsColsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No R package files found.
        /// </summary>
        public static string NoRPkgFound {
            get {
                return ResourceManager.GetString("NoRPkgFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tables to show in output!.
        /// </summary>
        public static string NoTablesReturned {
            get {
                return ResourceManager.GetString("NoTablesReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -OR not &apos;data.frame&apos; type.
        /// </summary>
        public static string NotDataframe {
            get {
                return ResourceManager.GetString("NotDataframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Not a data frame object..
        /// </summary>
        public static string NotDataframe2 {
            get {
                return ResourceManager.GetString("NotDataframe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Dataset is not a data.frame type..
        /// </summary>
        public static string NotdataframeType {
            get {
                return ResourceManager.GetString("NotdataframeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid License.
        /// </summary>
        public static string NoValidLic {
            get {
                return ResourceManager.GetString("NoValidLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be formatted using BSKyFormat. Object:.
        /// </summary>
        public static string ObjCantBSkyFormat {
            get {
                return ResourceManager.GetString("ObjCantBSkyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be formatted using BSkyFormat. Type not supported. Supported types are :.
        /// </summary>
        public static string ObjCantBSkyFormat2 {
            get {
                return ResourceManager.GetString("ObjCantBSkyFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -R.Net server from old session still running. Use task manager to close it..
        /// </summary>
        public static string OldSessionRunning {
            get {
                return ResourceManager.GetString("OldSessionRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. R.Net server from the old session still running (use task manager to kill it)..
        /// </summary>
        public static string OldSessionRunning2 {
            get {
                return ResourceManager.GetString("OldSessionRunning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading RDATA file may overwrite your current variables/objects in memory if variables/objects with the same name are already present in the RDATA file..
        /// </summary>
        public static string OpenRDataWarnMsgLine1 {
            get {
                return ResourceManager.GetString("OpenRDataWarnMsgLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cancel out of here and save your all your current variables/objects which you can load later if required..
        /// </summary>
        public static string OpenRDataWarnMsgLine2 {
            get {
                return ResourceManager.GetString("OpenRDataWarnMsgLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To save/load your current variables/object run following commands from BlueSky R command editor..
        /// </summary>
        public static string OpenRDataWarnMsgLine3 {
            get {
                return ResourceManager.GetString("OpenRDataWarnMsgLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To save:  save.image(file=&apos;filename.rdata&apos;) # filename.rdata is the file name where objects will be saved..
        /// </summary>
        public static string OpenRDataWarnMsgLine4 {
            get {
                return ResourceManager.GetString("OpenRDataWarnMsgLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To load:  load(file=&apos;filename.rdata&apos;) # filename.rdata is the file name from which objects will be loaded..
        /// </summary>
        public static string OpenRDataWarnMsgLine5 {
            get {
                return ResourceManager.GetString("OpenRDataWarnMsgLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;filename.rdata&apos; is filename with forward slashed path e.g. &apos;C:/myfolder/myobjects.rdata&apos;.
        /// </summary>
        public static string OpenRDataWarnMsgLine6 {
            get {
                return ResourceManager.GetString("OpenRDataWarnMsgLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed? [Variables with matching names will be overwritten]..
        /// </summary>
        public static string OpenRDataWarnMsgLine7 {
            get {
                return ResourceManager.GetString("OpenRDataWarnMsgLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To open a R script, you need to switch to the &apos;Output and Syntax&apos; window..
        /// </summary>
        public static string OpenRScriptInSynWin {
            get {
                return ResourceManager.GetString("OpenRScriptInSynWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the right hand pane of the &apos;Output and Syntax&apos; window and click File -&gt; Open in the &apos;R Command Editor&apos;..
        /// </summary>
        public static string OpenRScriptMenuPath {
            get {
                return ResourceManager.GetString("OpenRScriptMenuPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: package must be already installed using &apos;install package&apos; option..
        /// </summary>
        public static string PkgMustAlreadyInstalled {
            get {
                return ResourceManager.GetString("PkgMustAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure:.
        /// </summary>
        public static string PleaseMakeSure {
            get {
                return ResourceManager.GetString("PleaseMakeSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm....
        /// </summary>
        public static string PlzConfirm {
            get {
                return ResourceManager.GetString("PlzConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE SAVE YOUR WORK BEFORE APP BECOMES UNUSABLE..
        /// </summary>
        public static string PlzSavB4AppUnusable {
            get {
                return ResourceManager.GetString("PlzSavB4AppUnusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PlzWait {
            get {
                return ResourceManager.GetString("PlzWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while Dataset is Loading....
        /// </summary>
        public static string PlzWaitDatasetLoading {
            get {
                return ResourceManager.GetString("PlzWaitDatasetLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons could be one or more of the following:.
        /// </summary>
        public static string reasonsAre {
            get {
                return ResourceManager.GetString("reasonsAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation &gt; Install All required package(s) from CRAN..
        /// </summary>
        public static string RegPkgsMenuPath {
            get {
                return ResourceManager.GetString("RegPkgsMenuPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Split First.
        /// </summary>
        public static string RemoveSplit {
            get {
                return ResourceManager.GetString("RemoveSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function manipulates the dataset. Please remove the split and rerun the command..
        /// </summary>
        public static string RemoveSplitForDataManipulation {
            get {
                return ResourceManager.GetString("RemoveSplitForDataManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -OR required R package(s) are missing.
        /// </summary>
        public static string ReqRPkgMissing {
            get {
                return ResourceManager.GetString("ReqRPkgMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Required R package is not installed..
        /// </summary>
        public static string ReqRPkgNotInstalled {
            get {
                return ResourceManager.GetString("ReqRPkgNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart BlueSky Application.
        /// </summary>
        public static string RestartBSkyApp {
            get {
                return ResourceManager.GetString("RestartBSkyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to restart the Application for the changes to take effect..
        /// </summary>
        public static string RestartToApplyChanges {
            get {
                return ResourceManager.GetString("RestartToApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will take effect after restarting the application!.
        /// </summary>
        public static string RestartToApplyChanges2 {
            get {
                return ResourceManager.GetString("RestartToApplyChanges2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package(s) Installation Status:.
        /// </summary>
        public static string RPkgInstallStatus {
            get {
                return ResourceManager.GetString("RPkgInstallStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package names are case sensitive. Please check your R package name..
        /// </summary>
        public static string RPkgNameCaseSensitive {
            get {
                return ResourceManager.GetString("RPkgNameCaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Some issue on R side (like: required R package not loaded)..
        /// </summary>
        public static string RSideIssue {
            get {
                return ResourceManager.GetString("RSideIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Some issue on R side (like: required library not loaded, incorrect syntax)..
        /// </summary>
        public static string RSideIssue2 {
            get {
                return ResourceManager.GetString("RSideIssue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path you have selected does not contain any R zip package files. Try again..
        /// </summary>
        public static string RZipPkgNotInPath {
            get {
                return ResourceManager.GetString("RZipPkgNotInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save-As failed..
        /// </summary>
        public static string SaveAsFailed {
            get {
                return ResourceManager.GetString("SaveAsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        public static string SaveConfirmation {
            get {
                return ResourceManager.GetString("SaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Exit Command Editor?.
        /// </summary>
        public static string SaveExitCommandEditor {
            get {
                return ResourceManager.GetString("SaveExitCommandEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save commands before loading new script?.
        /// </summary>
        public static string SaveScriptPromptBeforeOpen {
            get {
                return ResourceManager.GetString("SaveScriptPromptBeforeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to other formats.
        /// </summary>
        public static string SaveToOtherFormat {
            get {
                return ResourceManager.GetString("SaveToOtherFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;Model Type&apos; and &apos;Model&apos; from the dropdowns on the right of the toolbar of the BlueSky Statistics main window.
        /// </summary>
        public static string SelectModelTypeAndModel {
            get {
                return ResourceManager.GetString("SelectModelTypeAndModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Installed Packages.
        /// </summary>
        public static string ShowInstalledRPkgs {
            get {
                return ResourceManager.GetString("ShowInstalledRPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Loaded Packages.
        /// </summary>
        public static string ShowLoadedPkgs {
            get {
                return ResourceManager.GetString("ShowLoadedPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;sinkimage&apos; not found in config file. Aborting....
        /// </summary>
        public static string sinkimageConfigKeyNotFound {
            get {
                return ResourceManager.GetString("sinkimageConfigKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;sinkregstrdgrph&apos; not found in config file. You cannot run Graphics from Command Editor..
        /// </summary>
        public static string sinkregstrdgrphConfigKeyNotFound {
            get {
                return ResourceManager.GetString("sinkregstrdgrphConfigKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait... Loading required R packages..
        /// </summary>
        public static string StatMsgPkgLoad {
            get {
                return ResourceManager.GetString("StatMsgPkgLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;tempsink&apos; not found in config file. Aborting....
        /// </summary>
        public static string tempsinkConfigKeyNotFound {
            get {
                return ResourceManager.GetString("tempsinkConfigKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected.
        /// </summary>
        public static string unexpected {
            get {
                return ResourceManager.GetString("unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Package.
        /// </summary>
        public static string UninstallPkg {
            get {
                return ResourceManager.GetString("UninstallPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload Package.
        /// </summary>
        public static string UnloadPkg {
            get {
                return ResourceManager.GetString("UnloadPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Package(s).
        /// </summary>
        public static string UserPkgs {
            get {
                return ResourceManager.GetString("UserPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - User&apos;s Session List is Empty.
        /// </summary>
        public static string UserSessListEmpty {
            get {
                return ResourceManager.GetString("UserSessListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more User Session Package(s) failed to load..
        /// </summary>
        public static string UsrSessPkgsLoadFailed {
            get {
                return ResourceManager.GetString("UsrSessPkgsLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Overwrite?.
        /// </summary>
        public static string WarnOverwrite {
            get {
                return ResourceManager.GetString("WarnOverwrite", resourceCulture);
            }
        }
    }
}
