//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueSky.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NoUICtrlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NoUICtrlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueSky.Properties.NoUICtrlResources", typeof(NoUICtrlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA.
        /// </summary>
        public static string AAA {
            get {
                return ResourceManager.GetString("AAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Model Class Window.
        /// </summary>
        public static string AddModelClassWinTitle {
            get {
                return ResourceManager.GetString("AddModelClassWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close this application?.
        /// </summary>
        public static string AppExitConfirmMsg {
            get {
                return ResourceManager.GetString("AppExitConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application?.
        /// </summary>
        public static string AppExitConfirmMsgTitle {
            get {
                return ResourceManager.GetString("AppExitConfirmMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured. App will Exit..
        /// </summary>
        public static string AppExitOnErrorMsg {
            get {
                return ResourceManager.GetString("AppExitOnErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting Application!.
        /// </summary>
        public static string AppExitOnErrorMsgTitle {
            get {
                return ResourceManager.GetString("AppExitOnErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example 1: foreign.
        /// </summary>
        public static string AskPkgNameExample1 {
            get {
                return ResourceManager.GetString("AskPkgNameExample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example 2: foreign, car, MASS.
        /// </summary>
        public static string AskPkgNameExample2 {
            get {
                return ResourceManager.GetString("AskPkgNameExample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string buttonAdd {
            get {
                return ResourceManager.GetString("buttonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Class.
        /// </summary>
        public static string buttonAddClass {
            get {
                return ResourceManager.GetString("buttonAddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string buttonApply {
            get {
                return ResourceManager.GetString("buttonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string buttonBrowse {
            get {
                return ResourceManager.GetString("buttonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string buttonClose {
            get {
                return ResourceManager.GetString("buttonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string buttonDefault {
            get {
                return ResourceManager.GetString("buttonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string buttonFindNext {
            get {
                return ResourceManager.GetString("buttonFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string buttonHelp {
            get {
                return ResourceManager.GetString("buttonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string buttonMoveDown {
            get {
                return ResourceManager.GetString("buttonMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string buttonMoveUp {
            get {
                return ResourceManager.GetString("buttonMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string buttonRemove {
            get {
                return ResourceManager.GetString("buttonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string buttonReplace {
            get {
                return ResourceManager.GetString("buttonReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string buttonReplaceAll {
            get {
                return ResourceManager.GetString("buttonReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string buttonReset {
            get {
                return ResourceManager.GetString("buttonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        public static string buttonSyntax {
            get {
                return ResourceManager.GetString("buttonSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add factors to Measure=Scale(Numeric) type..
        /// </summary>
        public static string CantAddFactorToScaleVar {
            get {
                return ResourceManager.GetString("CantAddFactorToScaleVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image Size Dialog.
        /// </summary>
        public static string ChangeImgSizDlgTitle {
            get {
                return ResourceManager.GetString("ChangeImgSizDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Command Editor.
        /// </summary>
        public static string CommandEditorPanelTitle {
            get {
                return ResourceManager.GetString("CommandEditorPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Window.
        /// </summary>
        public static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete variable?.
        /// </summary>
        public static string DeleteVarConfirmation {
            get {
                return ResourceManager.GetString("DeleteVarConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another column with same name exists. Please try another name..
        /// </summary>
        public static string DupColMsg {
            get {
                return ResourceManager.GetString("DupColMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Column Name.
        /// </summary>
        public static string DupColNameTitle {
            get {
                return ResourceManager.GetString("DupColNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter graphic image dimensions (in pixel) :.
        /// </summary>
        public static string EnterImgSizePrompt {
            get {
                return ResourceManager.GetString("EnterImgSizePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter model class name (case sensitive):.
        /// </summary>
        public static string EnterModelClassPrompt {
            get {
                return ResourceManager.GetString("EnterModelClassPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name(s) of one or more package(s).
        /// </summary>
        public static string EnterPkgNamesLine1 {
            get {
                return ResourceManager.GetString("EnterPkgNamesLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to separated by comma.(package names are case sensitive).
        /// </summary>
        public static string EnterPkgNamesLine2 {
            get {
                return ResourceManager.GetString("EnterPkgNamesLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Label.
        /// </summary>
        public static string ExistingLabel {
            get {
                return ResourceManager.GetString("ExistingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist!.
        /// </summary>
        public static string FileRecentRScriptNotFound {
            get {
                return ResourceManager.GetString("FileRecentRScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow search by selecting one or more columns:.
        /// </summary>
        public static string FindDatagridNarrowSearch {
            get {
                return ResourceManager.GetString("FindDatagridNarrowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Datagrid Window.
        /// </summary>
        public static string findDatagridTitle {
            get {
                return ResourceManager.GetString("findDatagridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Replace Window.
        /// </summary>
        public static string FindReplaceWinTitle {
            get {
                return ResourceManager.GetString("FindReplaceWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Variable Window.
        /// </summary>
        public static string FindVarGridWinTitle {
            get {
                return ResourceManager.GetString("FindVarGridWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Variable Name:.
        /// </summary>
        public static string FindVarName {
            get {
                return ResourceManager.GetString("FindVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find What:.
        /// </summary>
        public static string findwhat {
            get {
                return ResourceManager.GetString("findwhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Navigation Tree.
        /// </summary>
        public static string HideNavTreeText {
            get {
                return ResourceManager.GetString("HideNavTreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryMenuName {
            get {
                return ResourceManager.GetString("HistoryMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Height:.
        /// </summary>
        public static string ImgHeight {
            get {
                return ResourceManager.GetString("ImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Width:.
        /// </summary>
        public static string ImgWidth {
            get {
                return ResourceManager.GetString("ImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In selected text.
        /// </summary>
        public static string InSelTextChkBox {
            get {
                return ResourceManager.GetString("InSelTextChkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview the dialog and sub dialogs associated with the command below.&quot; +&quot;Clicking on the Syntax button will bring up the syntax in the Command Editor. &quot;+ &quot;Clicking on the HELP button will bring up the Help. Clicking on the buttons in the dialog will bring up sub-dialogs. The property grid displays the properties of the dialog..
        /// </summary>
        public static string InspectHelpText {
            get {
                return ResourceManager.GetString("InspectHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect Dialog Window.
        /// </summary>
        public static string InspectWinTitle {
            get {
                return ResourceManager.GetString("InspectWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Packages From Folder.
        /// </summary>
        public static string InstallFromZipTitle {
            get {
                return ResourceManager.GetString("InstallFromZipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invalid date/time..
        /// </summary>
        public static string InvalidDateTimeMsg {
            get {
                return ResourceManager.GetString("InvalidDateTimeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date/Time..
        /// </summary>
        public static string InvalidDateTimeTitle {
            get {
                return ResourceManager.GetString("InvalidDateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not valid for variable of type Measure = Scale(Numeric).
        /// </summary>
        public static string InvalidOperationOnScale {
            get {
                return ResourceManager.GetString("InvalidOperationOnScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Packages (manually loaded by user from.
        /// </summary>
        public static string lbl1UserPkg {
            get {
                return ResourceManager.GetString("lbl1UserPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools &gt; Packages &gt; Load user session package(s) ).
        /// </summary>
        public static string lbl2UserPkg {
            get {
                return ResourceManager.GetString("lbl2UserPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Logging:.
        /// </summary>
        public static string lblAdvancedLogging {
            get {
                return ResourceManager.GetString("lblAdvancedLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While loading CSV/Excel files, convert &quot;character&quot; columns to &quot;factor&quot;..
        /// </summary>
        public static string lblCharToFactor {
            get {
                return ResourceManager.GetString("lblCharToFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Title Color:.
        /// </summary>
        public static string lblCommandTitleColor {
            get {
                return ResourceManager.GetString("lblCommandTitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string lblDataTab {
            get {
                return ResourceManager.GetString("lblDataTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default instance name for MSSQL Full is MSSQLSERVER and for MSSQL Express is SQLEXPRESS.
        /// </summary>
        public static string lblDefaultInstanceName {
            get {
                return ResourceManager.GetString("lblDefaultInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Packages (loads with application:).
        /// </summary>
        public static string lblDefPkg {
            get {
                return ResourceManager.GetString("lblDefPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Model classes that will appear in the &apos;Model Type&apos; dropdown..
        /// </summary>
        public static string lblDropdownModels {
            get {
                return ResourceManager.GetString("lblDropdownModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Color:.
        /// </summary>
        public static string lblErrorColor {
            get {
                return ResourceManager.GetString("lblErrorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: C:/Program Files/R/R-3.2.1 (use forward slash &apos;/&apos; for path).
        /// </summary>
        public static string lblExampleRHomeDir {
            get {
                return ResourceManager.GetString("lblExampleRHomeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string lblFind {
            get {
                return ResourceManager.GetString("lblFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Image Height:.
        /// </summary>
        public static string lblImageHeight {
            get {
                return ResourceManager.GetString("lblImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Image Width:.
        /// </summary>
        public static string lblImageWidth {
            get {
                return ResourceManager.GetString("lblImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Directory:.
        /// </summary>
        public static string lblInitialDirectory {
            get {
                return ResourceManager.GetString("lblInitialDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter server instance name :.
        /// </summary>
        public static string lblInstanceName {
            get {
                return ResourceManager.GetString("lblInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please modify the server instance name if its different from the default..
        /// </summary>
        public static string lblInstanceNameNote {
            get {
                return ResourceManager.GetString("lblInstanceNameNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comma separated list of days (how many days before expiry, reminder should notify you. Blank field loads defaults. Enter 0 or 1 if you dont want to set any days):.
        /// </summary>
        public static string lblLicNotifyDays {
            get {
                return ResourceManager.GetString("lblLicNotifyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load SAV file&apos;s missing values:.
        /// </summary>
        public static string lblLoadMissing {
            get {
                return ResourceManager.GetString("lblLoadMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level:.
        /// </summary>
        public static string lblLogLevel {
            get {
                return ResourceManager.GetString("lblLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string lblMatchCaseChkBox {
            get {
                return ResourceManager.GetString("lblMatchCaseChkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        public static string lblMatchOptions {
            get {
                return ResourceManager.GetString("lblMatchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. No. Of Chars in Left Tree:.
        /// </summary>
        public static string lblMaxCharsNavTree {
            get {
                return ResourceManager.GetString("lblMaxCharsNavTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter maximum number of factor you want:.
        /// </summary>
        public static string lblMaxFactor {
            get {
                return ResourceManager.GetString("lblMaxFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse hover box color (in output pane):.
        /// </summary>
        public static string lblMouseHoverBoxColor {
            get {
                return ResourceManager.GetString("lblMouseHoverBoxColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation tree selected item box color (in output pane):.
        /// </summary>
        public static string lblNavTreeSelColor {
            get {
                return ResourceManager.GetString("lblNavTreeSelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Decimal Digits:.
        /// </summary>
        public static string lblNoDecimalDigits {
            get {
                return ResourceManager.GetString("lblNoDecimalDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Options window when opening dataset:.
        /// </summary>
        public static string lblOpenOptions {
            get {
                return ResourceManager.GetString("lblOpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size:.
        /// </summary>
        public static string lblPageSize {
            get {
                return ResourceManager.GetString("lblPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size:.
        /// </summary>
        public static string lblPDFFontSize {
            get {
                return ResourceManager.GetString("lblPDFFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comma separated margin values (Left, Top, Right, Bottom):.
        /// </summary>
        public static string lblPDFMargins {
            get {
                return ResourceManager.GetString("lblPDFMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter maximum number of table columns per page(including row header columns):.
        /// </summary>
        public static string lblPDFMaxCols {
            get {
                return ResourceManager.GetString("lblPDFMaxCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter maximum number of table rows per page(including column header rows):.
        /// </summary>
        public static string lblPDFMaxRows {
            get {
                return ResourceManager.GetString("lblPDFMaxRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace With:.
        /// </summary>
        public static string lblReplaceWith {
            get {
                return ResourceManager.GetString("lblReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain scientific notation for a very small number (eg.0.00001234, 1.234e-5, -0.00001234, -1.234e-5)..
        /// </summary>
        public static string lblRetainSciNotation {
            get {
                return ResourceManager.GetString("lblRetainSciNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Home Directory:.
        /// </summary>
        public static string lblRHomeDir {
            get {
                return ResourceManager.GetString("lblRHomeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Syntax Color:.
        /// </summary>
        public static string lblRSynColor {
            get {
                return ResourceManager.GetString("lblRSynColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The R object that contains the results of the analytical function may contain numeric row headers. This option determine whether the row headers are displayed or hidden. When checked, numeric row headers are shown in output grid:.
        /// </summary>
        public static string lblShowHideNumericHeaders {
            get {
                return ResourceManager.GetString("lblShowHideNumericHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Folder:.
        /// </summary>
        public static string lblTempFolder {
            get {
                return ResourceManager.GetString("lblTempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold number of values per output table for which warning will be displayed informing 
        ///                        the user that table generation will be time consuming and giving the user the choice to 
        ///                        display the partial results..
        /// </summary>
        public static string lblThresholdCount {
            get {
                return ResourceManager.GetString("lblThresholdCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micosoft SQL server Driver path:.
        /// </summary>
        public static string lblTitleDriverPath {
            get {
                return ResourceManager.GetString("lblTitleDriverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: C:/Program Files/Microsoft SQL Server JDBC Driver 3.0/sqljdbc_3.0/enu/sqljdbc4.jar.
        /// </summary>
        public static string lblTitleDriverPathExample {
            get {
                return ResourceManager.GetString("lblTitleDriverPathExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: You must use forward slash(/) in path..
        /// </summary>
        public static string lblTitleDriverPathNote {
            get {
                return ResourceManager.GetString("lblTitleDriverPathNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSSQL Server Instance:.
        /// </summary>
        public static string lblTitleServerInstance {
            get {
                return ResourceManager.GetString("lblTitleServerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on the row number to access functions, for eg. Add Factor Level, Change Label, Make Factor, Insert New Variable and Delete Variable.
        /// </summary>
        public static string lblVarGridContext {
            get {
                return ResourceManager.GetString("lblVarGridContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string lblVariablesTab {
            get {
                return ResourceManager.GetString("lblVariablesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Word.
        /// </summary>
        public static string lblWholeWordChkBox {
            get {
                return ResourceManager.GetString("lblWholeWordChkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Browse&apos; and locate your folder that contains R package zip files..
        /// </summary>
        public static string LocateZipMsg {
            get {
                return ResourceManager.GetString("LocateZipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached end. No more matches..
        /// </summary>
        public static string MatchEndReached {
            get {
                return ResourceManager.GetString("MatchEndReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus can&apos;t be generated....
        /// </summary>
        public static string MenuGenerationFailedMsg {
            get {
                return ResourceManager.GetString("MenuGenerationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuOutputEdit {
            get {
                return ResourceManager.GetString("MenuOutputEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MenuOutputEditCopy {
            get {
                return ResourceManager.GetString("MenuOutputEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string MenuOutputEditCut {
            get {
                return ResourceManager.GetString("MenuOutputEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string MenuOutputEditPaste {
            get {
                return ResourceManager.GetString("MenuOutputEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string MenuOutputEditRedo {
            get {
                return ResourceManager.GetString("MenuOutputEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string MenuOutputEditUndo {
            get {
                return ResourceManager.GetString("MenuOutputEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuOutputFile {
            get {
                return ResourceManager.GetString("MenuOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        public static string MenuOutputFileClose {
            get {
                return ResourceManager.GetString("MenuOutputFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open BlueSky Saved Output.
        /// </summary>
        public static string MenuOutputFileOpenOutput {
            get {
                return ResourceManager.GetString("MenuOutputFileOpenOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string MenuOutputFileSaveAs {
            get {
                return ResourceManager.GetString("MenuOutputFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As PDF.
        /// </summary>
        public static string MenuOutputFileSaveAsPDF {
            get {
                return ResourceManager.GetString("MenuOutputFileSaveAsPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size.
        /// </summary>
        public static string MenuOutputImageSize {
            get {
                return ResourceManager.GetString("MenuOutputImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Graphic Size.
        /// </summary>
        public static string MenuOutputImageSizeChange {
            get {
                return ResourceManager.GetString("MenuOutputImageSizeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default Graphic Size.
        /// </summary>
        public static string MenuOutputImageSizeDefault {
            get {
                return ResourceManager.GetString("MenuOutputImageSizeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string MenuOutputLayout {
            get {
                return ResourceManager.GetString("MenuOutputLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string MenuOutputLayoutHorizontal {
            get {
                return ResourceManager.GetString("MenuOutputLayoutHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Navigation Tree.
        /// </summary>
        public static string MenuOutputLayoutShowNavTree {
            get {
                return ResourceManager.GetString("MenuOutputLayoutShowNavTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string MenuOutputLayoutVertical {
            get {
                return ResourceManager.GetString("MenuOutputLayoutVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MenuSynEdit {
            get {
                return ResourceManager.GetString("MenuSynEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string MenuSynEditCopy {
            get {
                return ResourceManager.GetString("MenuSynEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string MenuSynEditCut {
            get {
                return ResourceManager.GetString("MenuSynEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find/Replace.
        /// </summary>
        public static string MenuSynEditFindReplace {
            get {
                return ResourceManager.GetString("MenuSynEditFindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string MenuSynEditPaste {
            get {
                return ResourceManager.GetString("MenuSynEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string MenuSynEditRedo {
            get {
                return ResourceManager.GetString("MenuSynEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string MenuSynEditUndo {
            get {
                return ResourceManager.GetString("MenuSynEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuSynFile {
            get {
                return ResourceManager.GetString("MenuSynFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MenuSynFileNew {
            get {
                return ResourceManager.GetString("MenuSynFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MenuSynFileOpen {
            get {
                return ResourceManager.GetString("MenuSynFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string MenuSynFileRecent {
            get {
                return ResourceManager.GetString("MenuSynFileRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuSynFileSave {
            get {
                return ResourceManager.GetString("MenuSynFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As.
        /// </summary>
        public static string MenuSynFileSaveAs {
            get {
                return ResourceManager.GetString("MenuSynFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: type lm without quotes and click &apos;Add Class&apos;.
        /// </summary>
        public static string ModelClassExample {
            get {
                return ResourceManager.GetString("ModelClassExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Unselect this node to show/hide in right pane.
        /// </summary>
        public static string NavTreeCheckboxTooltip {
            get {
                return ResourceManager.GetString("NavTreeCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to bring the item in the view.
        /// </summary>
        public static string NavTreeNodeTBTooltip {
            get {
                return ResourceManager.GetString("NavTreeNodeTBTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Label.
        /// </summary>
        public static string NewLabel {
            get {
                return ResourceManager.GetString("NewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Match.
        /// </summary>
        public static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found.
        /// </summary>
        public static string NoMatchFound {
            get {
                return ResourceManager.GetString("NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more matches.
        /// </summary>
        public static string NoMoreMatch {
            get {
                return ResourceManager.GetString("NoMoreMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value, you have entered a non-numeric value for a numeric variable. If you want to enter a non-numeric values make this variable a factor and enter non-numeric levels.
        /// </summary>
        public static string NonNumForNumVar {
            get {
                return ResourceManager.GetString("NonNumForNumVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: All the files in the folder must be R package .zip files..
        /// </summary>
        public static string NoteMsg {
            get {
                return ResourceManager.GetString("NoteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of Analysis.
        /// </summary>
        public static string OutputPanelTitle {
            get {
                return ResourceManager.GetString("OutputPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouput and Syntax Window-.
        /// </summary>
        public static string OutputWindowMainTitle {
            get {
                return ResourceManager.GetString("OutputWindowMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Active).
        /// </summary>
        public static string OutputWindowTitleStatus {
            get {
                return ResourceManager.GetString("OutputWindowTitleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the output of.
        /// </summary>
        public static string OutputWinSavePromptPart1 {
            get {
                return ResourceManager.GetString("OutputWinSavePromptPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes : Save all and Close,.
        /// </summary>
        public static string OutputWinSavePromptPart2 {
            get {
                return ResourceManager.GetString("OutputWinSavePromptPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel: Do not Save/Close this window..
        /// </summary>
        public static string OutputWinSavePromptPart3 {
            get {
                return ResourceManager.GetString("OutputWinSavePromptPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Output?.
        /// </summary>
        public static string OutputWinSavePromptTitle {
            get {
                return ResourceManager.GetString("OutputWinSavePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found!.
        /// </summary>
        public static string RecentScriptNotFoundMsgBoxTitle {
            get {
                return ResourceManager.GetString("RecentScriptNotFoundMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.xml not found....
        /// </summary>
        public static string RecentXMLnotfound {
            get {
                return ResourceManager.GetString("RecentXMLnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save commands before closing Command Editor?.
        /// </summary>
        public static string REditorCloseSaveScriptPrompt {
            get {
                return ResourceManager.GetString("REditorCloseSaveScriptPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only .r (R script) and .txt(plain text) files are supported..
        /// </summary>
        public static string REditorFileTypeSupportedMsg {
            get {
                return ResourceManager.GetString("REditorFileTypeSupportedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of text: No more occurrences. Search pointer will start from the begining..
        /// </summary>
        public static string REditorFindNextEndsMsg {
            get {
                return ResourceManager.GetString("REditorFindNextEndsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more match.
        /// </summary>
        public static string REditorFindNextEndsMsgbxTitle {
            get {
                return ResourceManager.GetString("REditorFindNextEndsMsgbxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some text in R Command Editor first.
        /// </summary>
        public static string REditorReplaceAllInSelectedMsg {
            get {
                return ResourceManager.GetString("REditorReplaceAllInSelectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Selected.
        /// </summary>
        public static string REditorReplaceAllInSelectedMsgboxTitle {
            get {
                return ResourceManager.GetString("REditorReplaceAllInSelectedMsgboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close current command script?.
        /// </summary>
        public static string REditorSavePromptMsgBoxTitle {
            get {
                return ResourceManager.GetString("REditorSavePromptMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save current script?.
        /// </summary>
        public static string REditorSaveScriptPrompt {
            get {
                return ResourceManager.GetString("REditorSaveScriptPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSky R scripts,.
        /// </summary>
        public static string RScriptFilenameFilter {
            get {
                return ResourceManager.GetString("RScriptFilenameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Current Dataset.
        /// </summary>
        public static string ScoringSectionTitle {
            get {
                return ResourceManager.GetString("ScoringSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more packages:.
        /// </summary>
        public static string SelOneOrMore {
            get {
                return ResourceManager.GetString("SelOneOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( Tip: Use Ctrl or Shift key for multi-select.).
        /// </summary>
        public static string SelOneOrMoreTip {
            get {
                return ResourceManager.GetString("SelOneOrMoreTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Packages Window.
        /// </summary>
        public static string SelPkgWinTitle {
            get {
                return ResourceManager.GetString("SelPkgWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select One Table/Sheet.
        /// </summary>
        public static string SelTableOrSheet {
            get {
                return ResourceManager.GetString("SelTableOrSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Worksheet Window.
        /// </summary>
        public static string SelWorksheetWin {
            get {
                return ResourceManager.GetString("SelWorksheetWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Navigation Tree.
        /// </summary>
        public static string ShowNavTreeText {
            get {
                return ResourceManager.GetString("ShowNavTreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For details, go to Help -&gt; Licensing)..
        /// </summary>
        public static string StatusbarLicInfo {
            get {
                return ResourceManager.GetString("StatusbarLicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split on :.
        /// </summary>
        public static string StatusbarSplitInfo {
            get {
                return ResourceManager.GetString("StatusbarSplitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Syntax generated by dialog.
        /// </summary>
        public static string syncomment {
            get {
                return ResourceManager.GetString("syncomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #There is no syntax associated with dialog.
        /// </summary>
        public static string syncomment2 {
            get {
                return ResourceManager.GetString("syncomment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### This is R syntax editor ###.
        /// </summary>
        public static string SynGetStrtMsg1 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### You can enter some R statements here and execute them..
        /// </summary>
        public static string SynGetStrtMsg2 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Type in few R statements..
        /// </summary>
        public static string SynGetStrtMsg3 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Select one or more, complete R statements..
        /// </summary>
        public static string SynGetStrtMsg4 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Click Run (blue triangle icon) from the toolbar above..
        /// </summary>
        public static string SynGetStrtMsg5 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### See the generated output on the output panel(on the left)..
        /// </summary>
        public static string SynGetStrtMsg6 {
            get {
                return ResourceManager.GetString("SynGetStrtMsg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyntaxRecent.xml not found..
        /// </summary>
        public static string SynRecentXmlNotFound {
            get {
                return ResourceManager.GetString("SynRecentXmlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string TabTitleAdvanced {
            get {
                return ResourceManager.GetString("TabTitleAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string TabTitleColors {
            get {
                return ResourceManager.GetString("TabTitleColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Packages.
        /// </summary>
        public static string TabTitleDefaultPackages {
            get {
                return ResourceManager.GetString("TabTitleDefaultPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string TabTitleImage {
            get {
                return ResourceManager.GetString("TabTitleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string TabTitleModels {
            get {
                return ResourceManager.GetString("TabTitleModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string TabTitleOthers {
            get {
                return ResourceManager.GetString("TabTitleOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Settings.
        /// </summary>
        public static string TabTitlePathSettings {
            get {
                return ResourceManager.GetString("TabTitlePathSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Settings.
        /// </summary>
        public static string TabTitlePDFSettings {
            get {
                return ResourceManager.GetString("TabTitlePDFSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Settings.
        /// </summary>
        public static string TabTitleSQLSettings {
            get {
                return ResourceManager.GetString("TabTitleSQLSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Packages.
        /// </summary>
        public static string TabTitleUserPackages {
            get {
                return ResourceManager.GetString("TabTitleUserPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this dataset.
        /// </summary>
        public static string ToolTipCloseDataset {
            get {
                return ResourceManager.GetString("ToolTipCloseDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted.
        /// </summary>
        public static string ToolTipSorted {
            get {
                return ResourceManager.GetString("ToolTipSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Level Warning:.
        /// </summary>
        public static string WarningAddRemoveLabel {
            get {
                return ResourceManager.GetString("WarningAddRemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Level Warning:.
        /// </summary>
        public static string WarningChangeLevel {
            get {
                return ResourceManager.GetString("WarningChangeLevel", resourceCulture);
            }
        }
    }
}
